context-path: ${APIGateway.context-path}

server:
  port: ${APIGateway.port}

management:
  endpoints:
    gateway:
      enabled: true
    web:
      exposure:
        include: health,gateway

spring:
  application:
    name: @project.build.finalName@
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
      routes:
      - id: UserProvisioningService
        uri: ${UserProvisioningService.url}
        predicates:
        - Path=${context-path}${UserProvisioningService.context-path}/**
        filters:
        - StripPrefix=1
      - id: UserService
        uri: ${UserService.url}
        predicates:
          - Path=${context-path}${UserService.context-path}/**
        filters:
          - StripPrefix=1
      - id: GoalService
        uri: ${GoalService.url}
        predicates:
          - Path=${context-path}${GoalService.context-path}/**
        filters:
          - StripPrefix=1
      - id: EventService
        uri: ${EventService.url}
        predicates:
          - Path=${context-path}${EventService.context-path}/**
        filters:
          - StripPrefix=1
